CREATE SEQUENCE order_sevice_id_seq
START WITH 0000000001
INCREMENT BY 1
MAXVALUE 999999999;
--order_service_id, order_id, service_id

INSERT INTO ORDERS_SERVICE VALUES (1, 1, 1);  
INSERT INTO ORDERS_SERVICE VALUES (2, 1, 2);  
INSERT INTO ORDERS_SERVICE VALUES (3, 2, 1); 
INSERT INTO ORDERS_SERVICE VALUES (4, 2, 3); 
INSERT INTO ORDERS_SERVICE VALUES (5, 3, 4); 
INSERT INTO ORDERS_SERVICE VALUES (6, 4, 1); 
INSERT INTO ORDERS_SERVICE VALUES (7, 5, 2); 
INSERT INTO ORDERS_SERVICE VALUES (8, 5, 3); 
INSERT INTO ORDERS_SERVICE VALUES (9, 6, 1);  
INSERT INTO ORDERS_SERVICE VALUES (10, 6, 4);